<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SAMPLE CUSTOMFIELD NUMBER_Sample Customfield Number</name>
   <tag></tag>
   <elementGuidId>17a6cea3-7034-4d10-9074-b474ba10e9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c8594376-5a36-4026-a542-bcb3671571f5-d48i6ea313-SampleCustomfieldNumber-PROF_INPUT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c8594376-5a36-4026-a542-bcb3671571f5-d48i6ea313-SampleCustomfieldNumber-PROF_INPUT</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @name = 'Sample Customfield Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sample Customfield Number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c8594376-5a36-4026-a542-bcb3671571f5-d48i6ea313-SampleCustomfieldNumber-PROF_INPUT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c8594376-5a36-4026-a542-bcb3671571f5-d48i6ea313-SampleCustomfieldNumber-PROF_INPUT&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c8594376-5a36-4026-a542-bcb3671571f5-d48i6ea313-SampleCustomfieldNumber-PROF_INPUT']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customfields']/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
